config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  resources :lists, except: :index do
    resources :bookmarks, only: [ :create ]
  end
  resources :bookmarks, only: [ :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates_uniqueness_of :list_id, scope: :movie_id
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
  validates :photo, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  # def new
  #   @bookmark = Bookmark.new
  #   @list = List.find(params[:list_id])
  # end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render "lists/show"
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @list = List.find(@bookmark.list_id)
    @bookmark.destroy
    redirect_to list_path(@list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
    # @movie = Movie.find[23]
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    if @list.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<div class="container">
  <%= simple_form_for([@list, @bookmark]) do |f| %>
    <%= f.input :comment %>
    <%= f.association :movie %>
    <%= f.submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/lists/index.html.erb
<div class="page-container">

  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <div>
      <%= link_to "#", class: "navbar-brand" do %>
        <%= image_tag "logo.gif", alt: "Watch list", width: 200 %>
      <% end %>
    </div>
    <div class="collapse navbar-collapse flex-row ml-md-auto d-none d-md-flex" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li>
          <%= link_to "Create a list", new_list_path, class:"btn btn-flat" %>
        </li>
      </ul>
    </div>
  </div>

  <div class=container>
    <div class="cards">
      <% @lists.each do |list| %>
        <%= link_to list.name, list_path(list), class:"card-category", style:"background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('#{cl_image_path(list.photo.key)}');" %>
      <% end %>
    </div>
  </div>


  <div class="footer">
    <div class="footer-links">
      <a href="#"><i class="fab fa-github"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>
    <div class="footer-copyright">
      This footer is made with <i class="fas fa-heart"></i> at Le Wagon
    </div>
  </div>
</div>

      <%# <%= link_to list.name, list_path(list), class:"card-category", style:"background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://source.unsplash.com/featured/?#{list.name.split(" ").join("%20")})" %>

app/views/lists/new.html.erb
<div class="page-container">

  <div class="container">
    <h1>Create a new list</h1>
    <div>
      <%= simple_form_for(@list) do |f| %>
        <%= f.input :name %>
        <%= f.input :photo, as: :file %>
        <%= f.submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="page-container">

  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <div>
      <%= link_to "#", class: "navbar-brand" do %>
        <%= image_tag "logo.gif", alt: "Watch list", width: 200 %>
      <% end %>
      <%= link_to "Lists", root_path, class: "btn btn-ghost mr-auto" %>
    </div>
    <div class="collapse navbar-collapse flex-row ml-md-auto d-none d-md-flex" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li>
          <%= link_to "Create a list", new_list_path, class:"btn btn-flat" %>
        </li>
      </ul>
    </div>
  </div>

  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path @list.photo.key, crop: :fill %>)">
      <h1><%= @list.name %></h1>
  </div>

  <div class="container">
    <button class="btn btn-ghost" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
      Create a bookmark
    </button>

    <div class="collapse" id="collapseExample">
      <%= simple_form_for([@list, @bookmark]) do |f| %>
        <%= f.association :movie %>
        <%= f.input :comment, hint: 'Minimum is 6 characters'  %>
        <%= f.submit "Add a movie", class:"btn btn-flat" %>
      <% end %>
    </div>
    <% if @list.bookmarks.empty? %>
      <div class="d-flex align-items-start">
        <%= image_tag "up-arrow.png", width: 100 %>
        <h1>Create your first bookmark !</h1>
      </div>
    <% else %>
      <div class="cards">
        <% @list.bookmarks.each do |bookmark| %>
          <div class="card-trip d-flex flex-column">
            <img src="<%= bookmark.movie.poster_url %>" />
              <div class="card-trip-infos">
                <div>
                  <p class="card-title"><strong><%= bookmark.movie.title %></strong> - <%= bookmark.movie.rating %>❤️</p>
                  <p><%= bookmark.movie.overview %></p>
                </div>
              </div>
              <div class="card-trip-infos mt-auto d-flex align-items-center justify-content-between">
                  <p class="card-comment"><i class="fas fa-angle-double-right"></i> <%= bookmark.comment %></p>
                  <%= link_to "delete", bookmark_path(bookmark), method: :delete %>
              </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="footer">
    <div class="footer-links">
      <a href="#"><i class="fab fa-github"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>
    <div class="footer-copyright">
      This footer is made with <i class="fas fa-heart"></i> at Le Wagon
    </div>
  </div>

</div>